---
nginx/nginx-1.11.13.tar.gz:
  size: 980784
  object_id: 214aec6b-e095-4b21-7155-d038f699eaae
  sha: 84f27729754796181dc39d47da761c7e85eb3ae2
nginx/pcre-8.40.tar.gz:
  size: 2065161
  object_id: 44706e8c-255c-4ff3-9737-23ab55a1a214
  sha: 10384eb3d411794cc15f55b9d837d3f69e35391e
golang/go1.8.3.linux-amd64.tar.gz:
  size: 90029041
  object_id: 53346f1f-edfc-40d5-54b9-04126e05fdf3
  sha: 838c415896ef5ecd395dfabde5e7e6f8ac943c8e
