language: node_js
node_js:
  - "12.13.0"
sudo: required
dist: bionic
services:
  - docker
addons:
  chrome: stable
before_install:
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1366x768x24"
  - sleep 3
install:
  - npm install
  - ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
filter_secrets: false
branches:
  only:
    - master
    - v2-master
    - e2e-tests
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"
    - node_modules
stages:
  - Lint
  - Build
  - Test
jobs:
  include:
    - stage: Lint
      name: Frontend Lint
      script:
        - npm run lint
    - name: Backend Lint
      before_script:
        - curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
        - chmod +x ~/bin/gimme
        - eval "$(gimme 1.13.4)"
        - go get -u golang.org/x/lint/golint
      script:
        - golint src/jetstream/...
        - ./deploy/ci/travis/update-go-report-card.sh
    - stage: Build
      name: Build Frontend and Backend
      env:
        - CI_ENV=true
      script:
        - "./deploy/ci/travis/e2e-build-script.sh build"
    - stage: Test
      name: Frontend Unit Tests
      env:
        - CI_ENV=true
      script:
        - npm run test
        - npm run codecov
    - name: Backend Unit Tests
      before_script:
        - curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
        - chmod +x ~/bin/gimme
        - eval "$(gimme 1.13.4)"
      script:
        - npm run test-backend
      after_success:
        - bash <(curl -s https://codecov.io/bash) -F backend

