language: node_js
node_js:
  - "6"
sudo: required
services:
  - docker
addons:
  chrome: stable  
install:
  - npm install
jobs:
  include:
    - stage: e2e tests
      before_script:
        - chmod +x ./deploy/ci/travis/e2e-allinone.sh
        - npm install -g bower
        - bower install
      script:
        - ./deploy/ci/travis/e2e-allinone.sh
    - stage: back-end
      before_script:
        - curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
        - chmod +x ~/bin/gimme
        - eval "$(gimme 1.9)"
        - curl https://glide.sh/get | sh
      script:
        - npm run test-backend
    - stage: front-end
      before_script:
        - npm install -g bower
        - bower install
      script:
        - npm build
        - npm run gate-check
