---
platform: linux
inputs:
- name: stra2ous
# Parameterised task files are currently not supported in Concourse
# Once that is implemented we can refactor the following into a variable
image_resource:
  type: docker-image
  source:
   repository:  ci-registry.ngrok.io:80/splatform/stratos-concourse
   tag: "latest"
   insecure_registries: [ "ci-registry.ngrok.io:80" ]

run:
  path: sh
  args:
    - -exc
    - |
      export CONCOURSE_ENV="true"
      cd stra2ous/
      npm install
      npm test