---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-encryption-key-volume"
  labels:
    app:  "{{ .Release.Name }}"
  annotations:
  {{- if .Values.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-upgrade-volume"
  labels:
    app:  "{{ .Release.Name }}"
  annotations:
  {{- if .Values.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app:  "{{ .Release.Name }}"
  name: "{{ .Release.Name }}-preflight-job"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
spec:
 template:
     metadata:
       labels:
         app:  "{{ .Release.Name }}"
         component: preflight
     spec:
       containers:
         - env:
           - name: UPGRADE_VOLUME
             value: "{{ .Release.Name }}-upgrade-volume"
           - name: UPGRADE_LOCK_FILENAME
             value: upgrade.lock
           - name: ENCRYPTION_KEY_VOLUME
             value: "{{ .Release.Name }}-encryption-key-volume"
           - name: ENCRYPTION_KEY_FILENAME
             value: key
           image: {{.Values.dockerRegistry}}/{{.Values.dockerOrg}}/{{.Values.images.preflight}}:{{.Values.consoleVersion}}
           name: "{{ .Release.Name }}-preflight-job"
           volumeMounts:
           - mountPath: "/{{ .Release.Name }}-upgrade-volume"
             name: "{{ .Release.Name }}-upgrade-volume"
           - mountPath: "/{{ .Release.Name }}-encryption-key-volume"
             name: "{{ .Release.Name }}-encryption-key-volume"
       restartPolicy: Never
       volumes:
       - name: "{{ .Release.Name }}-upgrade-volume"
         persistentVolumeClaim:
           claimName: "{{ .Release.Name }}-upgrade-volume"
       - name: "{{ .Release.Name }}-encryption-key-volume"
         persistentVolumeClaim:
           claimName: "{{ .Release.Name }}-encryption-key-volume"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-upgrade-job"
  labels:
    app: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-upgrade-job"
      labels:
        app: "{{ .Release.Name }}"
        component: upgrade-job
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: kubectl
        hostPath:
          path: /usr/bin/kubectl

      containers:
      - name: post-install-job
        image: "lachlanevenson/k8s-kubectl:v1.6.0"
        volumeMounts:
        - name: kubectl
          mountPath: /kubectl
        command:
        - sh
        - -c
        - "kubectl delete job --namespace {{ .Release.Namespace }} -l app={{ .Release.Name }}"
