apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-ext-service"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: "{{ .Release.Name }}-ui-ext"
spec:
  ports:
{{- if and (not .Values.useLb) (or (not .Values.kube.external_ip) (and .Values.kube.external_ip .Values.kube.external_console_http_port)) }}
  - name: http
    {{- if and (or .Values.kube.external_ip .Values.console.externalIP .Values.kube.external_ips) .Values.kube.external_console_http_port }}
    port: {{ .Values.kube.external_console_http_port }}
    {{- else }}
    port: 80
    {{- end }}
    protocol: TCP
    targetPort: 80
{{- end }}
  - name: https
{{- if and (or .Values.kube.external_ip .Values.console.externalIP .Values.kube.external_ips) .Values.kube.external_console_https_port }}
    port: {{ .Values.kube.external_console_https_port }}
{{- else }}
    port: {{ .Values.console.port }}
{{- end }}
    protocol: TCP
    targetPort: 443
  selector:
    app: "{{ .Release.Name }}"
    component: console
{{- if or .Values.useLb .Values.services.loadbalanced }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
{{- if or .Values.kube.external_ip .Values.console.externalIP .Values.kube.external_ips  }}
  externalIPs: {{ template "service.externalIPs" . }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mariadb"
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-mariadb-service"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "{{ .Release.Name }}"


