apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}-ui-ext"
spec:
  ports:
{{- if and (not .Values.useLb) (or (not .Values.kube.external_ip) (and .Values.kube.external_ip .Values.kube.external_console_http_port)) }}
  - name: http
    port: {{ default 80 .Values.kube.external_console_http_port }}
    protocol: TCP
    targetPort: 80
{{- end }}
  - name: https
{{- if and .Values.kube.external_ip .Values.kube.external_console_https_port }}
    port: {{ .Values.kube.external_console_https_port }}
{{- else }}
    port: 443
{{- end }}
    protocol: TCP
    targetPort: {{ .Values.console.port }}
  selector:
    app: "{{ .Release.Name }}"
    component: console
{{- if .Values.useLb }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
{{- if .Values.kube.external_ip }}
  externalIPs:
  -  {{ .Values.kube.external_ip }}
{{- else }}
  {{- if .Values.console.externalIP }}
  externalIPs:
  -  {{ .Values.console.externalIP }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mariadb"
  labels:
    app: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "{{ .Release.Name }}"
