apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-ext-service"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: "{{ .Release.Name }}-ui-ext"
spec:
# Note: HTTP Port is always optional - HTTPS port always included
{{- if or .Values.useLb .Values.services.loadbalanced }}
# Load Balancer configuration
  type: LoadBalancer
  ports:
{{- if .Values.console.http_port }}
  - name: http
    port: {{ .Values.console.http_port }}
    protocol: TCP
    targetPort: 80
{{- end }}
  - name: https
    port: {{ template "service.https_port" . }}
    protocol: TCP
    targetPort: 443
{{- else }}
{{- if or .Values.kube.external_ip .Values.console.externalIP .Values.kube.external_ips }}
# External IP(s) configured
  ports:
{{- if .Values.console.http_port }}
  - name: http
    port: {{ .Values.console.http_port }}
    protocol: TCP
    targetPort: 80
{{- end }}
  - name: https
    port: {{ template "service.https_port" . }}
    protocol: TCP
    targetPort: 443
  externalIPs: {{ template "service.externalIPs" . }}
{{- else }} # Not External IP
{{- if or .Values.console.https_port .Values.console.port .Values.kube.external_console_https_port }}
# NodePort configured
  type: NodePort
  ports:
{{- if .Values.console.http_port }}
  - name: http
    nodePort: {{ .Values.console.http_port }}
    protocol: TCP
    port: 80
{{- end }}
  - name: https
    nodePort: {{ template "service.https_port" . }}
    protocol: TCP
    port: 443
{{- else }}
# ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mariadb"
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-mariadb-service"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "{{ .Release.Name }}"


