---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   repository: governmentpaas/cf-cli 
   tag: latest

run:
  path: sh
  args:
    - -exc
    - |
      ping -c 5 api.cf-dev.io
      cf login --skip-ssl-validation -a ${CF_API_URL} -u ${CF_USER} -p ${CF_PASSWORD} -o ${CF_ORG} -s ${CF_SPACE}
      cd stratos-ui
      if [ ! -z ${CREATE_DB} ]; then
      cf create-service p-mysql 512mb console_db
      cat << EOF >> manifest.yml
      services:
      - console_db
      EOF
      cat manifest.yml;
      fi
      cf  push ${APP_NAME} --hostname ${APP_NAME}