---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   repository:  registry.capbristol.com:5000/opensuse
   tag: "latest"
   insecure_registries: ["registry.capbristol.com:5000"]
run:
  path: sh
  args:
    - -ec
    - |
      echo "Skip"