---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   repository: ci-registry.ngrok.io:80/stratos-bk-concourse
   tag: "latest"
   insecure_registries: [ "ci-registry.ngrok.io:80" ]

run:
  path: sh
  args:
    - -exc
    - |
      cd stratos-ui
      if [ "$(md5sum /package.json | cut -d' ' -f1)" != "$(md5sum package.json| cut -d' ' -f1)" ]; then
        echo -e "\033[31mpackage.json was updated, please update the image. Running npm install\033[0m"
        npm install
      else
        echo -e "\033[32mpackage.json has not changed. Skipping npm install\033[0m"
      fi
      npm run test-backend