resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
resources:
- name: stratos-ui
  type: git
  source:
    access_token: {{github-access-token}}
    branch: {{stratos-ui-branch}}
    repo: SUSE/stratos-ui
    uri: git@github.com:suse/stratos-ui.git
    private_key: {{github-private-key}}
    base_url: {{base-url}}

- name: send-email
  type: email
  source:
    smtp:
      host: {{email-server}}
      port: {{email-port}}
      username: {{email-username}}
      password: {{email-password}}
    from: {{email-from}}
    # to: [ "irfan.habib@suse.com", "neil.macdougall@suse.com", "richard.cox@suse.com", "njones@suse.com" ]
    to: [ "irfan.habib@suse.com" ]

groups:
- name: tests
  jobs:
  - update-concourse-image
  - update-bk-concourse-image

jobs:
- name: update-concourse-image
  plan:
  - get: stratos-ui
    trigger: true
  - do:
    - task: update-concourse-build-image
      privileged: true
      timeout: 20m
      file: stratos-ui/deploy/ci/tasks/update-images/update-concourse-image.yml
      params:
        DOCKER_USERNAME: {{docker-username}}
        DOCKER_PASSWORD: {{docker-password}}
        DOCKER_ORG: {{docker-build-org}}
        TAG: {{docker-build-tag}}
      on_failure:
        put: send-email
        params:
          subject_text: "Concourse Image update ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} failed!"
          body_text: "Concourse Image update has failed: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
 
- name: update-bk-concourse-image
  plan:
  - get: stratos-ui
    trigger: true
    passed: [update-concourse-image]
  - do:
    - task: update-bk-concourse-build-image
      privileged: true
      timeout: 20m
      file: stratos-ui/deploy/ci/tasks/update-images/update-bk-concourse-image.yml
      params:
        DOCKER_USERNAME: {{docker-username}}
        DOCKER_PASSWORD: {{docker-password}}
        DOCKER_ORG: {{docker-build-org}}
        TAG: {{docker-build-tag}}
      on_failure:
        put: send-email
        params:
          subject_text: "Concourse Image update ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} failed!"
          body_text: "Concourse Image update has failed: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
      on_success:
        put: send-email
        params:
          subject_text: "Concourse Image update ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} successful"
          body_text: "Concourse Image update build was successful: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
