---
resources:
# Stratos Git Repository
- name: helm-release
  type: github-release
  source:
    owner: ((helm-repo-github-organization))
    repository: ((helm-repo-github-repository))
    access_token: ((github-access-token))
    tag_filter: 2\.[0-9]*\.[0-9]*
# Stratos Git Repository
- name: stratos
  type: git
  source:
    uri: git@github.com:((stratos-repository-organization))/((stratos-repository))
    branch: ((stratos-repository-branch))
    private_key: ((github-private-key))
jobs:
- name: make-chart-pr
  plan:
  - get: helm-release
    trigger: true
  - get: stratos
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos/deploy/ci/tasks/dev-releases/create-helm-pr.yml
      params:
        GIT_USER: ((concourse-user))
        GIT_EMAIL: ((concourse-email))
        GITHUB_USER: ((helm-repo-github-organization))
        GITHUB_ORG: ((helm-repo-github-organization))
        GITHUB_REPO: ((helm-repo-github-repository))
        GITHUB_TOKEN: ((github-access-token))
        GIT_PRIVATE_KEY: ((github-private-key))
        GITHUB_TOKEN: ((github-access-token))
        DOCKER_ORG: ((docker-organization))
        DOCKER_REGISTRY: ((docker-registry))
        HELM_REPO_PATH: ((helm-repo-path))
        HELM_REPO_BRANCH: ((helm-repo-branch))

