resources:
- name: stratos-ui
  type: git
  source:
    branch: {{stratos-ui-branch}}
    private_key: {{github-private-key}}
    uri: git@github.com:suse/stratos-ui.git
    tag_filter: "[0-9]*"
- name: helm-chart-values
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/values.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-Chart
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/Chart.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-tarball
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/console-(?P<version>.*).tgz
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-values-sle
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/values.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-Chart-sle
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/Chart.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-tarball-sle
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/console-(?P<version>.*).tgz
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1

groups:
- name: tests
  jobs:
  - build-opensuse-helm-images
  - build-sle-helm-images
  - update-repo
  - create-sle-chart
  - update-github-release

jobs:
- name: build-opensuse-helm-images
  plan:
  - get: stratos-ui
    trigger: true
  - do:
    - task: generete-certs
      timeout: 2m
      file: stratos-ui/deploy/ci/tasks/build-images/generate-certs.yml
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/build-helm.yml
      params:
        DOCKER_USERNAME: {{docker-username}}
        DOCKER_PASSWORD: {{docker-password}}
        BASE_IMAGE: opensuse
        REGISTRY: docker.io
    - put: helm-chart-values
      params:
        file: helm-build/values.yaml-*
        acl: public-read
    - put: helm-chart-Chart
      params:
        file: helm-build/Chart.yaml-*
        acl: public-read
- name: build-sle-helm-images
  plan:
  - get: stratos-ui
    trigger: true
  - do:
    - task: generete-certs
      timeout: 2m
      file: stratos-ui/deploy/ci/tasks/build-images/generate-certs.yml
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/build-helm.yml
      params:
        DOCKER_USERNAME: {{docker-username}}
        DOCKER_PASSWORD: {{docker-password}}
        BASE_IMAGE: sle_12
        STAGING_REPOSITORY: {{staging-repository}}
    - put: helm-chart-values-sle
      params:
        file: helm-build/values.yaml-*
        acl: public-read
    - put: helm-chart-Chart-sle
      params:
        file: helm-build/Chart.yaml-*
        acl: public-read


- name: update-repo
  plan:
  - get: stratos-ui
    passed: [build-opensuse-helm-images]
    trigger: true
  - get: helm-chart-Chart
    passed: [build-opensuse-helm-images]
  - get: helm-chart-values
    passed: [build-opensuse-helm-images]
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/create-chart.yml
      params:
        GIT_USER: {{concourse-user}}
        GIT_EMAIL: {{concourse-email}}
        GITHUB_ORG: {{github-organization}}
        GITHUB_REPO: {{github-repository}}
        GIT_PRIVATE_KEY: {{github-private-key}}
    - put: helm-chart-tarball
      params:
        file: helm-chart/*.tgz
        acl: public-read

- name: create-sle-chart
  plan:
  - get: stratos-ui
    passed: [build-sle-helm-images]
    trigger: true
  - get: helm-chart-Chart-sle
    passed: [build-sle-helm-images]
  - get: helm-chart-values-sle
    passed: [build-sle-helm-images]
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/create-chart.yml
      params:
        GIT_USER: {{concourse-user}}
        GIT_EMAIL: {{concourse-email}}
        GITHUB_ORG: {{github-organization}}
        GITHUB_REPO: {{github-repository}}
        GIT_PRIVATE_KEY: {{github-private-key}}
        NO_REPO: "true"
        BASE_IMAGE: "sle"
    - put: helm-chart-tarball-sle
      params:
        file: helm-chart/*.tgz
        acl: public-read

- name: update-github-release
  plan:
  - get: stratos-ui
    passed: [update-repo]
    trigger: true
  - get: helm-chart-tarball
    passed: [update-repo]
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/update-gh-release.yml
      params:
        GITHUB_TOKEN: {{github-access-token}}
        CHANDLER_GITHUB_API_TOKEN: {{github-access-token}}
        GITHUB_USER: {{github-organization}}
        GITHUB_REPO: {{github-repository}}
