---
resource_types:
- name: stratos-git-resource
  type: docker-image
  source:
    repository: splatform/stratos-git-tag-resource
resources:
# Stratos Git Repository
- name: stratos
  type: stratos-git-resource
  source:
    uri: git@github.com:((stratos-repository-organization))/((stratos-repository))
    branch: ((stratos-repository-branch))
    private_key: ((github-private-key))
    # Match stable tag
    tag_filter: "stable"
- name: helm-repo
  type: git
  source:
    uri: git@github.com:((helm-repo-github-organization))/((helm-repo-github-repository))
    branch: ((helm-repo-branch))
    private_key: ((github-private-key))
# Artifacts
- name: image-tag
  type: s3
  source:
    bucket: ((minio-bucket))
    endpoint: ((minio-server-endpoint))
    regexp: temp-artifacts/release-(.*).tar
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-access-key))
    region_name: eu-central-1
jobs:
- name: generate-tag-files
  plan:
  - get: stratos
    trigger: true
  - do:
    - task: generate-tag
      file: stratos/deploy/ci/tasks/dev-releases/generate-tag-files.yml
      params:
        TAG_SUFFIX: ((tag-suffix))
    - put: image-tag
      params:
        file: image-tag/*.tar
        acl: public-read
- name: make-release
  plan:
  - get: stratos
    passed: [generate-tag-files]
    trigger: true
  - get: helm-repo
  - get: image-tag
    passed: [generate-tag-files]
    params:
      unpack: true
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos/deploy/ci/tasks/dev-releases/make-release.yml
      params:
        GIT_USER: ((concourse-user))
        GIT_EMAIL: ((concourse-email))
        GITHUB_USER: ((helm-repo-github-organization))
        GITHUB_ORG: ((helm-repo-github-organization))
        GITHUB_REPO: ((helm-repo-github-repository))
        GITHUB_TOKEN: ((github-access-token))
        GIT_PRIVATE_KEY: ((github-private-key))
        DOCKER_ORG: ((docker-organization))
        DOCKER_REGISTRY: ((docker-registry))
        HELM_REPO_PATH: ((helm-repo-path))
        HELM_REPO_BRANCH: ((helm-repo-branch))
        SOURCE_REPO_ORG: ((stratos-repository-organization))
        SOURCE_REPO_REPO: ((stratos-repository))
        HELM_MIRROR_BASE_URL: ((web-server-base-url))
        HELM_RELEASE_GITCLONE: ((release-helm-repo))
        HELM_RELEASE_REPO_NAME: ((release-helm-repo-name))
        HELM_RELEASE_REPO_BRANCH: ((release-helm-repo-branch))
        HELM_RELEASE_REPO_FOLDER: ((release-helm-stable-folder))
        HELM_RELEASE_REGISTRY_HOST: ((release-repository))
        HELM_RELEASE_REGISTRY_ORG: ((release-repository-organization))
        TAG_SUFFIX: ((tag-suffix))
