resources:
- name: stratos-ui
  type: git
  source:
    repo: SUSE/stratos-ui
    uri: https://github.com/cloudfoundry-incubator/stratos.git
    branch: all-in-one

- name: aio-image
  type: docker-image
  source:
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{docker-io-aio-repository}}

jobs:
- name: publish-image
  public: true
  serial: true
  plan:
  - get: stratos-ui
  - put: aio-image
    params:
      build: stratos-ui/
      dockerfile: stratos-ui/deploy/Dockerfile.all-in-one



