version: '2.3'
services:

  ##############################################################################
  # These two "services" are not meant to be instantiated, but instead extended.
  # This is necessary for those who require a web proxty.
  ##############################################################################

  imageCommon:
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}


  buildCommon:
    extends: imageCommon
    build:
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - no_proxy=${no_proxy}
        - stratos_version=${stratos_version}

  ##############################################################################


  mariadb:
    extends: buildCommon
    build:
      context: ../deploy/db
      dockerfile: Dockerfile.mariadb
    env_file:
      ./mariadb.env
    ports:
      - "3306:3306"


  db-migrator:
    extends: buildCommon
    build:
      context: ../
      dockerfile: deploy/Dockerfile.bk
      target: db-migrator
    environment:
      - DATABASE_PROVIDER=mysql


  proxy:
    extends: buildCommon
    build:
      context: ../
      dockerfile: deploy/Dockerfile.bk
      target: dev-build
    ports:
      - "3003:3003"
    env_file:
      ./proxy.env
     
  nginx:
    extends: buildCommon
    build:
      context: ../
      dockerfile: deploy/Dockerfile.ui
      target: dev-build
    ports:
      - 80:80
      - 443:443

  uaa:
    extends: imageCommon
    # NOTE: This is required so that the tests run against
    # a UAA instance that has all the correct roles
    image: splatform/stratos-uaa
