version: '2.3'
services:

  # The development docker-compose file.
  # Use this to have things like "gulp watch" running in the UI.

  ui:
    extends:
      file: common.yml
      service: ui

  mariadb:
    extends:
      file: common.yml
      service: mariadb

  goose:
    extends:
      file: common.yml
      service: goose
    links:
      - mariadb:mariadb

  proxy:
    extends:
      file: common.yml
      service: proxy
    links:
      - goose:goose
      - uaa:uaa


  nginx:
    extends:
      file: common.yml
      service: nginx
    links:
      - proxy:proxy


  uaa:
    extends:
      file: common.yml
      service: uaa
