version: '2'
services:

  # The development docker-compose file.
  # Use this to have things like "gulp watch" running in the UI.

  ui:
    extends:
      file: common.yml
      service: ui
    environment:
       - CUSTOM_APP_LABEL=${CUSTOM_APP_LABEL}
    build:
      dockerfile: deploy/ci/Dockerfile.test
    links:
      - nginx


  postgres:
    extends:
      file: common.yml
      service: postgres


  goose:
    extends:
      file: common.yml
      service: goose
    links:
      - postgres


  proxy:
    extends:
      file: common.yml
      service: proxy
    links:
      - goose
      - uaa:uaa

  nginx:
    extends:
      file: common.yml
      service: nginx
    links:
      - proxy

  uaa:
    extends:
      file: common.yml
      service: uaa
