{{- $v := $.Files.Get "fdbvalues.yaml" | fromYaml }}
{{- if semverCompare ">=1.16" (printf "%s.%s" .Capabilities.KubeVersion.Major (trimSuffix "+" .Capabilities.KubeVersion.Minor) )}}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-fdbdoclayer
  labels:
    app: {{ template "fullname" . }}-fdbdoclayer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ $v.fdbdoclayer.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-fdbdoclayer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-fdbdoclayer
        release: {{ .Release.Name }}
    spec:
{{- with $v.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: fdbdoclayer
        image: {{ template "fdb.image" $v.fdbdoclayer.image }}
        volumeMounts:
        - name: certs
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: FDB_COORDINATOR
          value: {{ template "fullname" . }}-fdbserver
        - name: CLUSTER_ID
          value: chartdb:erlklkg
        - name: ENABLE_TLS
          value: $v.fdbdoclayer.tls
        ports:
        - containerPort: {{ $v.fdbdoclayer.service.port }}
        livenessProbe:
          tcpSocket:
            port: {{ $v.fdbdoclayer.service.port }}
          initialDelaySeconds: 3
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: {{ $v.fdbdoclayer.service.port }}
          initialDelaySeconds: 3
          periodSeconds: 10
      volumes:
        - name: certs
          secret:
            secretName: {{ template "fullname" . }}-fdbdoclayer-certs