
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fdbdoclayer
  labels:
    app: {{ template "fullname" . }}-fdbdoclayer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.fdbdoclayer.service.port }}
    targetPort: {{ .Values.fdbdoclayer.service.port }}
    protocol: TCP
    name: {{ .Values.fdbdoclayer.service.name }}
  selector:
    app: {{ template "fullname" . }}-fdbdoclayer
    release: {{ .Release.Name }}