{{- $v := $.Files.Get "fdbvalues.yaml" | fromYaml }}
{{- if semverCompare ">=1.16" (printf "%s.%s" .Capabilities.KubeVersion.Major (trimSuffix "+" .Capabilities.KubeVersion.Minor) )}}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-fdbserver
  labels:
    app: {{ template "fullname" . }}-fdbserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ $v.fdbserver.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-fdbserver
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-fdbserver
        release: {{ .Release.Name }}
    spec:
{{- with $v.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: fdbserver
        image: {{ template "fdb.image" $v.fdbserver.image }}
        env:
        - name: FDB_COORDINATOR
          value: {{ template "fullname" . }}-fdbserver.console.svc.cluster.local
        - name: CLUSTER_ID
          value: chartdb:erlklkg
        ports:
        - containerPort: {{ $v.fdbserver.service.port }}
        livenessProbe:
          tcpSocket:
            port: {{ $v.fdbserver.service.port }}
          initialDelaySeconds: 3
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: {{ $v.fdbserver.service.port }}
          initialDelaySeconds: 3
          periodSeconds: 10