---
platform: linux
inputs:
- name: stratos-ui
- name: dev-certs-output
image_resource:
  type: docker-image
  source:
   repository:  10.84.93.11:5000/concourse-dcind
   tag: "latest"
   insecure_registries: [ "10.4.21.241:5000" ]

run:
  path: sh
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      # Move dev-certs
      ls .
      mv dev-certs-output/dev-certs stratos-ui/dev-certs
      cd stratos-ui/deploy/docker-compose/
      ./build.sh -t test -r 10.84.93.11:5000
