---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source: {repository: "stackatotest/hsc-concourse", tag: "latest"}
run:
  path: sh
  args:
    - -exc
    - |
      cd stratos-ui/tools/
      cp -r /node_modules .
      if [ "$(md5sum /package.json | cut -d' ' -f1)" != "$(md5sum package.json| cut -d' ' -f1)" ]; then
        echo -e "\033[31mpackage.json was updated, please update the image. Running npm install\033[0m"
        npm install
      else
        echo -e "\033[32mpackage.json has not changed. Skipping npm install\033[0m"
      fi
      node_modules/.bin/bower --allow-root install
      npm run gate-check
