# Tag for images
consoleVersion: latest
dockerRegistrySecret: regsecret
# Specify default DB password
dbPassword: changeme
dbProvider: mysql
# Provide Proxy settings if required
#httpProxy: proxy.corp.net
#httpsProxy: proxy.corp.net
#noProxy: localhost
#ftpProxy: proxy.corp.net
#socksProxy: sock-proxy.corp.net
imagePullPolicy: IfNotPresent
# useLb is deprecated - use console.service.type
useLb: false
console:
  cookieDomain:
  # externalIP deprecated - use console.service.externalIPs
# externalIP: 127.0.0.1
  backendLogLevel: info
  ssoLogin: false
  ssoOptions:

  # Stratos Services
  service:
    annotations: []
    externalIPs: []
    loadBalancerIP:
    loadBalancerSourceRanges: []
    servicePort: 443
    # nodePort: 30000
    type: ClusterIP
    externalName:
    http:
      enabled: false
      servicePort: 80
      # nodePort: 30001
images:
  console: stratos-console
  proxy: stratos-jetstream
  postflight: stratos-postflight-job
  mariadb: stratos-mariadb

# Specify which storage class should be used for PVCs
#storageClass: default
#consoleCert: |
#    -----BEGIN CERTIFICATE-----
#   MIIDXTCCAkWgAwIBAgIJAJooOiQWl1v1MA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
#   ...
#    -----END CERTIFICATE-----
#consoleCertKey: |
#    -----BEGIN PRIVATE KEY-----
#    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkdgEAAoIBAQDV9+ySh0xZzM41
#    ...
#    -----END PRIVATE KEYE-----
# MariaDB chart configuration
mariadb:
  # Only required for creating the databases
  mariadbRootPassword: changeme
  adminUser: root
  # Credentials for user
  mariadbUser: console
  mariadbPassword: changeme
  mariadbDatabase: console
  usePassword: true
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass:
uaa:
  protocol: https://
  port: 
  host: 
  consoleClient:  
  consoleClientSecret: 
  consoleAdminIdentifier: 
  skipSSLValidation: false
# SCF values compatability 
env:
  DOMAIN:
  UAA_HOST: 
  UAA_PORT: 2793
kube:
  external_console_https_port: 8443
  storage_class:
    persistent:
  organization: splatform
  registry:
    hostname: docker.io
    username:
    password:
    email: default
services:
  loadbalanced: false
metrics:
  enabled: false