# Tag for images
consoleVersion: latest
# Docker Org
dockerOrg: splatform
# Docker Registry where images are available
dockerRegistry: docker.io
# Specify default DB password
dbPassword: changeme
# Provide Proxy settings if required
#httpProxy: proxy.corp.net
#httpsProxy: proxy.corp.net
#noProxy: localhost
#ftpProxy: proxy.corp.net
#socksProxy: sock-proxy.corp.net
noShared: false
images:
  console: stratos-console
  proxy: stratos-proxy
  proxyNoShared: stratos-proxy-noshared
  postgres: stratos-postgres
  preflight: stratos-preflight-job
  postflight: stratos-postflight-job
# Specify which storage class should be used for PVCs
#storageClass: default
# MariaDB chart configuration
mariadb:
  usePassword: true
  mariadbRootPassword: changeme
  persistence:
    enabled: true
    existingClaim: true
    accessMode: ReadWrite
    size: 1Gi
#    storageClass: default
  metrics:
    enabled: false
