---
platform: linux
inputs:
- name: stratos-ui
- name: dev-certs-output
outputs:
- name: helm-build
image_resource:
  type: docker-image
  source:
   repository:  ci-registry.capbristol.com:5000/concourse-dcind
   tag: "latest"
   insecure_registries: [ "ci-registry.capbristol.com:5000" ]

run:
  path: sh
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      cat /etc/docker/daemon.json
      # Login to Docker to push images
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${STAGING_REPOSITORY};
      ROOT_DIR=${PWD}
      # Move dev-certs
      mv ${ROOT_DIR}/dev-certs-output/dev-certs stratos-ui/dev-certs
      cd ${ROOT_DIR}/stratos-ui/deploy/kubernetes

      STRATOS_BOWER=""

      if [ ! -z "${IS_OFFICIAL}" ]; then
      ADD_OFFICIAL_TAG="-cap"
      STRATOS_BOWER="-u cap"
      fi
      # Build images
      if [ ! -z "${STAGING_REPOSITORY}" ]; then
      ./build.sh -T -c -b ${BASE_IMAGE} -r ${STAGING_REPOSITORY} -O ${STRATOS_BOWER}
      else
      ./build.sh -T -c -b ${BASE_IMAGE} ${STRATOS_BOWER}
      fi
      GIT_TAG="$(git describe $(git rev-list --tags --max-count=1))-$(git rev-parse --short HEAD)"
      cp console/values.yaml ${ROOT_DIR}/helm-build/values.yaml${ADD_OFFICIAL_TAG}-${GIT_TAG}
      cp console/Chart.yaml ${ROOT_DIR}/helm-build/Chart.yaml${ADD_OFFICIAL_TAG}-${GIT_TAG}
