---
platform: linux
inputs:
- name: stratos-ui
- name: helm-chart-Chart
- name: helm-chart-values
outputs:
- name: helm-chart
image_resource:
  type: docker-image
  source:
   repository:  10.4.21.241:5000/linkyard/helm
   tag: "latest"
   insecure_registries: [ "10.4.21.241:5000" ]

run:
  path: sh
  args:
    - -exc
    - |

      # Expect this command to fail since k8s isn't available but it will initialise helm locally
      helm init || true
      ROOT_DIR=$PWD
      STRATOS_UI=${ROOT_DIR}/stratos-ui
      cd ${STRATOS_UI}/deploy/kubernetes/
      GIT_TAG="$(git describe $(git rev-list --tags --max-count=1))-$(git rev-parse --short HEAD)"
      SHORT_GIT_TAG="$(git describe $(git rev-list --tags --max-count=1))"

      cp -f ${ROOT_DIR}/helm-chart-values/values.yaml* console/values.yaml
      cp -f ${ROOT_DIR}/helm-chart-Chart/Chart.yaml* console/Chart.yaml

      # Generate Helm package
      helm package console
      cp console*.tgz ${ROOT_DIR}/helm-chart/console-helm-chart.tgz
      cd ${ROOT_DIR}/helm-chart/
      if [ -f ${STRATOS_UI}/index.yaml ]; then
        cp ${STRATOS_UI}/index.yaml ${ROOT_DIR}/helm-chart/
        MERGE_INDEX="--merge index.yaml"
      fi

      # Update Helm Repository
      helm repo index ./ ${MERGE_INDEX} --url https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${SHORT_GIT_TAG}/
      cp index.yaml ${STRATOS_UI}/
      cd ${STRATOS_UI}
      git config --global user.name ${GIT_USER}
      git config --global user.email ${GIT_EMAIL}

      mkdir -p /root/.ssh/
      echo "${GIT_PRIVATE_KEY}" > /root/.ssh/id_rsa
      chmod 600 /root/.ssh/id_rsa

      # Update Helm repo
      git add index.yaml
      git commit -m "Helm repository updated for tag: ${GIT_TAG}"
      git config --global push.default simple
      git push origin HEAD:master
